name: client
version: 0.0.1
dependencies:
  angular: '>=0.12.0 <0.13.0'
  browser: '>=0.10.0+2 <0.11.0'
  uuid: '>=0.3.2 <0.4.0'
  
dev_dependencies:
  unittest: '>=0.11.0+2 <0.12.0'
   
transformers:
- angular

