name: redstone_angular_todo
version: 0.0.1
dependencies:
  angular: '>=1.0.0 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
  #client:
  #  path: ../client/
  connection_pool: '>=0.1.0+2 <0.2.0'
  mongo_dart: '>=0.1.45 <0.2.0'
  redstone: '>=0.5.19 <0.6.0'
  redstone_mapper: '>=0.1.9 <0.2.0'
  redstone_mapper_mongo: '>=0.1.1+1 <0.2.0'
  http: any

dev_dependencies:
  unittest: '>=0.11.0+2 <0.12.0'

transformers:
- redstone_mapper
- angular:
    dart_sdk: /www/dart-sdk/latest

