name: server
dependencies:
  client:
    path: ../client/
  connection_pool: '>=0.1.0+2 <0.2.0'
  mongo_dart: '>=0.1.42 <0.2.0'
  redstone: '>=0.5.6 <0.6.0'
  redstone_mapper: '>=0.1.1 <0.2.0'
  redstone_mapper_mongo: '>=0.1.1+1 <0.2.0'

  